services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: testDocker        # Replace with your desired username
      POSTGRES_PASSWORD: enzo  # Replace with your desired password
      POSTGRES_DB: SM_DB       # Replace with your desired database name
    ports:
      - "5432:5432"                 # Maps PostgreSQL's default port to your host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
      
volumes:
  postgres_data:
